"""Initial

Revision ID: 1803ecf3917d
Revises: 
Create Date: 2025-04-06 20:49:19.699838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1803ecf3917d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('auth_token', sa.String(length=100), nullable=False),
    sa.Column('refresh_token', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('client_secret', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('status_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_init', sa.String(length=100), server_default='', nullable=True),
    sa.Column('semantic', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_status_id'), 'stages', ['status_id'], unique=False)
    op.create_table('work_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_working_day', sa.Boolean(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=True),
    sa.Column('work_end', sa.Time(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='Когда создан'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False, comment='Когда обновлён'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='Кем создан'),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False, comment='Ответственный'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='Компания'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Воронка'),
    sa.Column('moved_time', sa.DateTime(timezone=True), nullable=False, comment='Когда передвинут'),
    sa.Column('moved_by', sa.Integer(), nullable=False, comment='Кем передвинут'),
    sa.Column('stage_id', sa.Integer(), nullable=False, comment='Стадия'),
    sa.Column('stage_id_str', sa.String(length=255), nullable=False, comment='Стадия абревиатура'),
    sa.Column('previous_stage_id', sa.String(length=255), nullable=False, comment='Предыдущая стадия'),
    sa.Column('opportunity', sa.Float(), nullable=True, comment='Сумма'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='ID_изделия_смарт'),
    sa.Column('product_type', sa.Integer(), nullable=True, comment='Тип изделия'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время перевода на стадию'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Время завершения нахождения на стадии'),
    sa.Column('work_time', sa.Interval(), nullable=False, comment='Время на стадии, только рабочее время'),
    sa.Column('non_work_time', sa.Interval(), nullable=False, comment='Время нахождения на стадии'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_history')
    op.drop_table('entities')
    op.drop_table('work_calendar')
    op.drop_index(op.f('ix_stages_status_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_table('credentials')
    # ### end Alembic commands ###
