"""Add new field

Revision ID: 22f8186c9b4c
Revises: 383cf895eebc
Create Date: 2025-05-15 22:08:21.101673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f8186c9b4c'
down_revision: Union[str, None] = '383cf895eebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_order', sa.Column('priority', sa.String(length=16), nullable=True, comment='Приоритет'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_order', 'priority')
    # ### end Alembic commands ###
