"""Add table of stage histories

Revision ID: 260cbec4a294
Revises: 22f8186c9b4c
Create Date: 2025-05-18 13:38:17.090098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260cbec4a294'
down_revision: Union[str, None] = '22f8186c9b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('stage_id_str', sa.String(length=255), nullable=False, comment='Стадия - абревиатура'),
    sa.Column('moved_time', sa.DateTime(timezone=True), nullable=False, comment='Когда передвинут'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_stage_history')
    # ### end Alembic commands ###
