"""add new field

Revision ID: 274d9ec60f39
Revises: 8534a6eb520b
Create Date: 2025-05-03 15:55:19.727357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274d9ec60f39'
down_revision: Union[str, None] = '8534a6eb520b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_order', sa.Column('entity_type_id', sa.Integer(), nullable=True, comment='Идентификатор типа смарт процесса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_order', 'entity_type_id')
    # ### end Alembic commands ###
