"""Change name field

Revision ID: 383cf895eebc
Revises: 3e6846cf8085
Create Date: 2025-05-11 16:48:02.705558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '383cf895eebc'
down_revision: Union[str, None] = '3e6846cf8085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_schedule', sa.Column('entity_type_id', sa.Integer(), nullable=True, comment='Идентификатор типа смарт процесса'))
    op.add_column('production_schedule', sa.Column('production_date', sa.DateTime(timezone=True), nullable=False, comment='Дата производства'))
    op.drop_column('production_schedule', 'production_вate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_schedule', sa.Column('production_вate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Дата производства'))
    op.drop_column('production_schedule', 'production_date')
    op.drop_column('production_schedule', 'entity_type_id')
    # ### end Alembic commands ###
