"""Change field

Revision ID: 3e6846cf8085
Revises: 274d9ec60f39
Create Date: 2025-05-04 23:39:36.593183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6846cf8085'
down_revision: Union[str, None] = '274d9ec60f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_order', sa.Column('production_date', sa.DateTime(timezone=True), nullable=True, comment='Дата производства'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_order', 'production_date')
    # ### end Alembic commands ###
