"""bitrix_settings

Revision ID: 41c603160847
Revises: 058914508fe4
Create Date: 2024-11-18 23:57:07.139291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c603160847'
down_revision: Union[str, None] = '058914508fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitrix_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('auth_token', sa.String(length=100), nullable=False),
    sa.Column('refresh_token', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitrix_settings')
    # ### end Alembic commands ###
